// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pathify.Models;

#nullable disable

namespace Pathify.Migrations
{
    [DbContext(typeof(PathifyContext))]
    [Migration("20260426154554_AddStudentFields")]
    partial class AddStudentFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Pathify.Controllers.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AcademicLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("EnrollmentYear")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("GPA")
                        .HasColumnType("float");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SSN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Pathify.Models.AdminPhone", b =>
                {
                    b.Property<string>("AdminSsn")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("AdminSSN");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("AdminSsn", "PhoneNumber")
                        .HasName("PK__Admin_ph__BF0595A377126546");

                    b.ToTable("Admin_phone", (string)null);
                });

            modelBuilder.Entity("Pathify.Models.Adminstration", b =>
                {
                    b.Property<string>("AdminSsn")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("AdminSSN");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FName");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(101)
                        .HasColumnType("nvarchar(101)")
                        .HasComputedColumnSql("(([FName]+' ')+[LName])", false);

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LName");

                    b.Property<string>("ManagerSsn")
                        .IsRequired()
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("managerSSN");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("AdminSsn");

                    b.HasIndex("ManagerSsn");

                    b.ToTable("Adminstration", (string)null);
                });

            modelBuilder.Entity("Pathify.Models.Course", b =>
                {
                    b.Property<string>("CourseId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Course_Id");

                    b.Property<string>("AdminSsn")
                        .IsRequired()
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("AdminSSN");

                    b.Property<int>("CourseLevel")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Course_Name");

                    b.Property<string>("CourseSemester")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Course_semester");

                    b.Property<int>("CreditHours")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PreReqCourseId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PreReqCourseID");

                    b.HasKey("CourseId")
                        .HasName("PK__Courses__37E005DBC529ABC7");

                    b.HasIndex("AdminSsn");

                    b.HasIndex("CourseLevel");

                    b.HasIndex("PreReqCourseId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Pathify.Models.Enrollment", b =>
                {
                    b.Property<string>("CourseId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Course_Id");

                    b.Property<string>("StudentSsn")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("StudentSSN");

                    b.Property<string>("AdminSsn")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("AdminSSN");

                    b.Property<DateOnly?>("EnrollmentDate")
                        .HasColumnType("date")
                        .HasColumnName("Enrollment_Date");

                    b.Property<bool?>("Passed")
                        .HasColumnType("bit")
                        .HasColumnName("passed");

                    b.HasKey("CourseId", "StudentSsn")
                        .HasName("PK__Enrollme__BDD4E4F595056AF2");

                    b.HasIndex("AdminSsn");

                    b.HasIndex("StudentSsn");

                    b.ToTable("Enrollment", (string)null);
                });

            modelBuilder.Entity("Pathify.Models.ExternalProfessor", b =>
                {
                    b.Property<string>("ExternalProfessorSsn")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("external_professor_SSN");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("dept_name");

                    b.Property<string>("ExternalProfessorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("external_professor_name");

                    b.HasKey("ExternalProfessorSsn")
                        .HasName("PK__External__2CA6D419ACC08BAD");

                    b.ToTable("External_Professor", (string)null);
                });

            modelBuilder.Entity("Pathify.Models.ExternalProfessorPhone", b =>
                {
                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("phone_number");

                    b.Property<string>("ExternalProfessorSsn")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("external_professor_SSN");

                    b.HasKey("PhoneNumber", "ExternalProfessorSsn")
                        .HasName("PK__External__2359072B2B737C0D");

                    b.HasIndex("ExternalProfessorSsn");

                    b.ToTable("External_Professor_phone", (string)null);
                });

            modelBuilder.Entity("Pathify.Models.InternalProfessor", b =>
                {
                    b.Property<string>("InternalProfessorSsn")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("Internal_professor_SSN");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("dept_name");

                    b.Property<string>("InternalProfessorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Internal_professor_name");

                    b.HasKey("InternalProfessorSsn")
                        .HasName("PK__Internal__251BDFA849DE7D95");

                    b.ToTable("Internal_Professor", (string)null);
                });

            modelBuilder.Entity("Pathify.Models.InternalProfessorPhone", b =>
                {
                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("phone_number");

                    b.Property<string>("InternalProfessorSsn")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("Internal_professor_SSN");

                    b.HasKey("PhoneNumber", "InternalProfessorSsn")
                        .HasName("PK__Internal__33C2D790883CEC2A");

                    b.HasIndex("InternalProfessorSsn");

                    b.ToTable("Internal_Professor_phone", (string)null);
                });

            modelBuilder.Entity("Pathify.Models.Level", b =>
                {
                    b.Property<int>("LevelId")
                        .HasColumnType("int")
                        .HasColumnName("LevelID");

                    b.Property<string>("LevelName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("LevelId")
                        .HasName("PK__Levels__09F03C061CA2AE55");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("Pathify.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<string>("ExternalProfessorSsn")
                        .IsRequired()
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("external_professor_SSN");

                    b.Property<string>("InternalProfessorSsn")
                        .IsRequired()
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("internal_professor_SSN");

                    b.Property<string>("ProjectDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Project_description");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("project_name");

                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    b.HasKey("ProjectId")
                        .HasName("PK__project___BC799E1FF0F2C05A");

                    b.HasIndex("ExternalProfessorSsn");

                    b.HasIndex("InternalProfessorSsn");

                    b.ToTable("project", (string)null);
                });

            modelBuilder.Entity("Pathify.Models.Student", b =>
                {
                    b.Property<string>("StudentSsn")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("StudentSSN");

                    b.Property<string>("AcademicLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EnrollmentYear")
                        .HasColumnType("int");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FName");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(101)
                        .HasColumnType("nvarchar(101)")
                        .HasComputedColumnSql("(([FName]+' ')+[LName])", false);

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("Gpa")
                        .HasColumnType("decimal(3, 2)")
                        .HasColumnName("GPA");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int?>("LevelId")
                        .HasColumnType("int")
                        .HasColumnName("LevelID");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LName");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    b.HasKey("StudentSsn")
                        .HasName("PK__Students__A34E12E9FC908EE4");

                    b.HasIndex("ProjectId");

                    b.HasIndex(new[] { "StudentId" }, "UQ__Students__32C52A78EC5DD016")
                        .IsUnique()
                        .HasFilter("[StudentID] IS NOT NULL");

                    b.HasIndex(new[] { "Email" }, "UQ__Students__A9D10534243C9339")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Pathify.Models.StudentPhone", b =>
                {
                    b.Property<string>("StudentSsn")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("StudentSSN");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("StudentSsn", "PhoneNumber")
                        .HasName("PK__student___2B11A60A9ECCBC2D");

                    b.ToTable("student_phone", (string)null);
                });

            modelBuilder.Entity("Pathify.Models.Supervisor", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<string>("InternalProfessorSsn")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("internal_professor_SSN");

                    b.Property<string>("ExternalProfessorSsn")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("external_professor_SSN");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("project_name");

                    b.HasKey("ProjectId", "InternalProfessorSsn", "ExternalProfessorSsn")
                        .HasName("PK__supervis__FFC582F35A74EF39");

                    b.HasIndex("ExternalProfessorSsn");

                    b.HasIndex("InternalProfessorSsn");

                    b.ToTable("supervisors", (string)null);
                });

            modelBuilder.Entity("SelectedCourse", b =>
                {
                    b.Property<string>("StudentSsn")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)");

                    b.Property<string>("CourseId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StudentSsn", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("SelectedCourses", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Pathify.Controllers.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Pathify.Controllers.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pathify.Controllers.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Pathify.Controllers.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pathify.Models.AdminPhone", b =>
                {
                    b.HasOne("Pathify.Models.Adminstration", "AdminSsnNavigation")
                        .WithMany("AdminPhones")
                        .HasForeignKey("AdminSsn")
                        .IsRequired()
                        .HasConstraintName("FK_Admin_phone_Adminstration");

                    b.Navigation("AdminSsnNavigation");
                });

            modelBuilder.Entity("Pathify.Models.Adminstration", b =>
                {
                    b.HasOne("Pathify.Models.Adminstration", "ManagerSsnNavigation")
                        .WithMany("InverseManagerSsnNavigation")
                        .HasForeignKey("ManagerSsn")
                        .IsRequired()
                        .HasConstraintName("FK_Adminstration_Adminstration");

                    b.Navigation("ManagerSsnNavigation");
                });

            modelBuilder.Entity("Pathify.Models.Course", b =>
                {
                    b.HasOne("Pathify.Models.Adminstration", "AdminSsnNavigation")
                        .WithMany("Courses")
                        .HasForeignKey("AdminSsn")
                        .IsRequired()
                        .HasConstraintName("FK_Courses_Adminstration");

                    b.HasOne("Pathify.Models.Level", "CourseLevelNavigation")
                        .WithMany("Courses")
                        .HasForeignKey("CourseLevel")
                        .IsRequired()
                        .HasConstraintName("FK_Courses_Levels");

                    b.HasOne("Pathify.Models.Course", "PreReqCourse")
                        .WithMany("InversePreReqCourse")
                        .HasForeignKey("PreReqCourseId")
                        .HasConstraintName("FK_Courses_Courses");

                    b.Navigation("AdminSsnNavigation");

                    b.Navigation("CourseLevelNavigation");

                    b.Navigation("PreReqCourse");
                });

            modelBuilder.Entity("Pathify.Models.Enrollment", b =>
                {
                    b.HasOne("Pathify.Models.Adminstration", "AdminSsnNavigation")
                        .WithMany("Enrollments")
                        .HasForeignKey("AdminSsn")
                        .HasConstraintName("FK_Enrollment_Adminstration");

                    b.HasOne("Pathify.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_Enrollment_Courses");

                    b.HasOne("Pathify.Models.Student", "StudentSsnNavigation")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentSsn")
                        .IsRequired()
                        .HasConstraintName("FK_Enrollment_Students");

                    b.Navigation("AdminSsnNavigation");

                    b.Navigation("Course");

                    b.Navigation("StudentSsnNavigation");
                });

            modelBuilder.Entity("Pathify.Models.ExternalProfessorPhone", b =>
                {
                    b.HasOne("Pathify.Models.ExternalProfessor", "ExternalProfessorSsnNavigation")
                        .WithMany("ExternalProfessorPhones")
                        .HasForeignKey("ExternalProfessorSsn")
                        .IsRequired()
                        .HasConstraintName("FK_External_Professor_phone_External_Professor");

                    b.Navigation("ExternalProfessorSsnNavigation");
                });

            modelBuilder.Entity("Pathify.Models.InternalProfessorPhone", b =>
                {
                    b.HasOne("Pathify.Models.InternalProfessor", "InternalProfessorSsnNavigation")
                        .WithMany("InternalProfessorPhones")
                        .HasForeignKey("InternalProfessorSsn")
                        .IsRequired()
                        .HasConstraintName("FK_Internal_Professor_phone_Internal_Professor");

                    b.Navigation("InternalProfessorSsnNavigation");
                });

            modelBuilder.Entity("Pathify.Models.Project", b =>
                {
                    b.HasOne("Pathify.Models.ExternalProfessor", "ExternalProfessorSsnNavigation")
                        .WithMany("Projects")
                        .HasForeignKey("ExternalProfessorSsn")
                        .IsRequired()
                        .HasConstraintName("FK_project_team_External_Professor");

                    b.HasOne("Pathify.Models.InternalProfessor", "InternalProfessorSsnNavigation")
                        .WithMany("Projects")
                        .HasForeignKey("InternalProfessorSsn")
                        .IsRequired()
                        .HasConstraintName("FK_project_team_Internal_Professor");

                    b.Navigation("ExternalProfessorSsnNavigation");

                    b.Navigation("InternalProfessorSsnNavigation");
                });

            modelBuilder.Entity("Pathify.Models.Student", b =>
                {
                    b.HasOne("Pathify.Models.Project", "Project")
                        .WithMany("Students")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK_Students_project");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Pathify.Models.StudentPhone", b =>
                {
                    b.HasOne("Pathify.Models.Student", "StudentSsnNavigation")
                        .WithMany("StudentPhones")
                        .HasForeignKey("StudentSsn")
                        .IsRequired()
                        .HasConstraintName("FK_student_phone_Students");

                    b.Navigation("StudentSsnNavigation");
                });

            modelBuilder.Entity("Pathify.Models.Supervisor", b =>
                {
                    b.HasOne("Pathify.Models.ExternalProfessor", "ExternalProfessorSsnNavigation")
                        .WithMany("Supervisors")
                        .HasForeignKey("ExternalProfessorSsn")
                        .IsRequired()
                        .HasConstraintName("FK_supervisors_External_Professor");

                    b.HasOne("Pathify.Models.InternalProfessor", "InternalProfessorSsnNavigation")
                        .WithMany("Supervisors")
                        .HasForeignKey("InternalProfessorSsn")
                        .IsRequired()
                        .HasConstraintName("FK_supervisors_Internal_Professor");

                    b.HasOne("Pathify.Models.Project", "Project")
                        .WithMany("Supervisors")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("FK_supervisors_project_team");

                    b.Navigation("ExternalProfessorSsnNavigation");

                    b.Navigation("InternalProfessorSsnNavigation");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SelectedCourse", b =>
                {
                    b.HasOne("Pathify.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_SelectedCourses_Course");

                    b.HasOne("Pathify.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentSsn")
                        .IsRequired()
                        .HasConstraintName("FK_SelectedCourses_Student");
                });

            modelBuilder.Entity("Pathify.Models.Adminstration", b =>
                {
                    b.Navigation("AdminPhones");

                    b.Navigation("Courses");

                    b.Navigation("Enrollments");

                    b.Navigation("InverseManagerSsnNavigation");
                });

            modelBuilder.Entity("Pathify.Models.Course", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("InversePreReqCourse");
                });

            modelBuilder.Entity("Pathify.Models.ExternalProfessor", b =>
                {
                    b.Navigation("ExternalProfessorPhones");

                    b.Navigation("Projects");

                    b.Navigation("Supervisors");
                });

            modelBuilder.Entity("Pathify.Models.InternalProfessor", b =>
                {
                    b.Navigation("InternalProfessorPhones");

                    b.Navigation("Projects");

                    b.Navigation("Supervisors");
                });

            modelBuilder.Entity("Pathify.Models.Level", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Pathify.Models.Project", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Supervisors");
                });

            modelBuilder.Entity("Pathify.Models.Student", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("StudentPhones");
                });
#pragma warning restore 612, 618
        }
    }
}
